name: Latest blog post workflow
on:
  schedule:
    # Runs every saturday at 9:30PM
    - cron: "0 0 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to and Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ankan101" #https://dev.to/feed/ankanbag06 returns 404 error
      - name: Generate eating snake svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg
